### ISSUE TITLE
CO2 sensor reporting humidity data?

### ISSUE THREAD

**Issue by snoack** [aqicn/gaia-a08-arduino#5]
I don't have a device to test it, but just looking at the [code](https://github.com/aqicn/gaia-a08-arduino/blob/97b38a5242e52dde3b4546f30509bd6543426d22/src/uploader.hpp#L72) it appears that the humidity data are uploading in place of the CO2 data?

**Comment by Ronaphil** [comment]
@ronanj this was resolved in #7

**Comment by snoack** [comment]
Issue is still visible in current master.

https://github.com/aqicn/gaia-a08-arduino/blob/926b9792b9915023379eab5b459707aa635ae329/src/sensors.cpp#L95-L97
